In [1]:
import numpy as np

In [2]:
#H5

a= np.random.randint(1,10, size=(3,5))
a

array([[8, 3, 3, 1, 4],
       [4, 9, 1, 3, 7],
       [3, 6, 4, 2, 3]])

In [3]:
#H6
a1 = np.zeros(10, dtype = int)
a1[5] = 3
a1


array([0, 0, 0, 0, 0, 3, 0, 0, 0, 0])

In [5]:
#H7
a2 = np.arange(3,15)
a2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#H8 
a3 = np.array([1, 3, 5, 2, 4, 5])
b3 = a3.reshape(3,2)
c3 = a3.reshape(2,3)

print(a3)
print('\n')
print(b3)
print('\n')
print(c3)


[1 3 5 2 4 5]


[[1 3]
 [5 2]
 [4 5]]


[[1 3 5]
 [2 4 5]]


In [17]:
#H2

def div(x,y):
    assert y!=0, 'Can’t divide'
    return x/y

div(6,0)

AssertionError: Can’t divide